### ISSUE TITLE
Adding a field that needs parsing

### ISSUE THREAD

**Issue by dariooddenino** [paluh/purescript-polyform-records-playground#1]
Hi! I'm studying this example and I'm trying to add a date field to the form. I'm not very familiar with some of the concepts used here, so it's probably quite simple to solve.

This is what I have so far (I'm only pasting my changes):
```
-- | Validation.purs
dateFormat :: Formatter
dateFormat = fromFoldable [ YearFull, Placeholder "-", MonthTwoDigits, Placeholder "-", DayOfMonthTwoDigits ]

unformatDate :: String -> Either String Date
unformatDate = ((<$>) date) <<< unformat dateFormat

invalidDate :: ∀ m err
  . Monad m
 => Validation m (Array (Variant (invalidDate :: Tuple String String | err))) String Date
invalidDate = Validation.hoistFnV \str ->
  case unformatDate str of
    Right d -> pure d
    Left err -> Invalid [ inj (SProxy :: SProxy "invalidDate") (Tuple err str) ]

-- | SignupForm.purs

signupForm = lift3 { password: _, email: _, date: _ } <$> passwordForm <*> emailForm <*> dateForm

type FormFieldsT f =
  ( email     :: f String
  , password1 :: f String
  , password2 :: f String
  , date      :: f Date
  )

_date      = SProxy :: SProxy "date"

buildDateForm v = formFromField _.date DateField v dateFieldValidation

type EmailError = Variant
  ( malformed :: String
  , inUse :: String
  )

dateFieldValidation :: ∀ m
  . Monad m
 => Validation m (Array DateError) String Date
dateFieldValidation = invalidDate

dateForm = buildDateForm
  { value: Invalid []
  , inputValue: inj _date
  , inputValidate: inj _date
  , label: "Date"
  }           
```

I get a compiler error in the last block of code, saying that it can't match String with Date. This is because `inputValue` is supposed to set a `Date` and I'm assuming it expects a `String` as input.

Isn't this transformation already handled by the validation function? Do I have to convert it again there? What's an elegant way to handle the fact that `unformatDate` returns an `Either String Date` and not a `Date`?

Thanks :)

**Comment by dariooddenino** [comment]
Ok I guess that's because `date` in `FormFieldsT` has to be `f String` instead of `f Date`. It seems like I've got everything working right now :) 

Sorry for the noise

**Comment by thomashoneyman** [comment]
Exactly! If I'm understanding your example correctly, the issue was simply that you were specifying the input as already a `Date` when your validation and everything is expecting a `String` input. I'm marking this as closed, but please re-open if there's more!
